# ========== Mapping ==========
map alt+n send_text all \x1b[D
map alt+u send_text all \x1b[B
map alt+i send_text all \x1b[A
map alt+m send_text all \x1b[C

# ========== Font ==========
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

# ========== Cursor ==========
cursor_shape     block
cursor_blink_interval 0.6
cursor_stop_blinking_after 15.0

# ========== Window ==========
window_padding_width 21

# ========== Scrollback ==========
scrollback_lines 5000
scrollback_pager less

# Bell
enable_audio_bell yes

# === Tokyo Night ===

# Tokyo Night Custom Theme
# https://github.com/arozx/kitty-tokyo-night-storm
# Inspired by: https://github.com/tokyo-night/tokyo-night-vscode-theme

# 16-color ANSI palette:
# Black: UI elements, comments, and subtle elements
# Red: Errors, deletions
# Green: Strings, success states
# Yellow: Warnings, constants, decorators
# Blue: Keywords, functions, method names
# Magenta: Built-ins, special keywords, classes
# Cyan: Parameters, types, symbols
# White: Standard light text and highlights

foreground #a9b1d6
background #24283b

# Black
color0 #414868
color8 #414868

# Red
color1 #f7768e
color9 #f7768e

# Green
color2  #73daca
color10 #73daca

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #c0caf5
color15 #c0caf5

# Cursor
cursor #c0caf5
cursor_text_color #24283b

# Selection highlight
selection_foreground none
selection_background #3d59a1
#! The selection background colour was changed to improve readability when selecting something

# The color for highlighting URLs on mouse-over
url_color #9ece6a

# Window borders
active_border_color #3d59a1
inactive_border_color #101014
bell_border_color #e0af68

# Tab bar
# tab_bar_style fade
# tab_fade 1
# active_tab_foreground   #3d59a1
# active_tab_background   #1f2335
# active_tab_font_style   bold
# inactive_tab_foreground #787c99
# inactive_tab_font_style bold
# inactive_tab_background #1f2335
# tab_bar_background #101014

# Title bar
# macos_titlebar_color #1f2335
