# ========== Mapping ==========
map alt+n send_text all \x1b[D
map alt+u send_text all \x1b[B
map alt+i send_text all \x1b[A
map alt+m send_text all \x1b[C

# ========== Font ==========
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
font_size        11.0

# ========== Cursor ==========
cursor_shape     block
cursor_blink_interval 0.6
cursor_stop_blinking_after 15.0

# ========== Window ==========
window_padding_width 21

# ========== Scrollback ==========
scrollback_lines 5000
scrollback_pager less

# ========== Bell ==========
enable_audio_bell no

# ========== Theme ==========
# Tokyo Night Storm background
# Nord Frost accents

foreground #D8DEE9
background #24283B

# Black
color0  #2F3549
color8  #414868

# Red
color1  #BF616A
color9  #D06F79

# Green
color2  #A3BE8C
color10 #B1D196

# Yellow
color3  #EBCB8B
color11 #F3D9A2

# Blue
color4  #5E81AC
color12 #81A1C1

# Magenta
color5  #B48EAD
color13 #C895BF

# Cyan
color6  #88C0D0
color14 #8FDFE8

# White
color7  #D8DEE9
color15 #ECEFF4

# ========== Cursor ==========
cursor #88C0D0
cursor_text_color #24283B

# ========== Selection ==========
selection_foreground #ECEFF4
selection_background #364A82

# ========== URL ==========
url_color #88C0D0

# ========== Borders ==========
active_border_color   #81A1C1
inactive_border_color #414868
bell_border_color     #EBCB8B

# ========== Tabs ==========
active_tab_foreground   #ECEFF4
active_tab_background   #5E81AC

inactive_tab_foreground #D8DEE9
inactive_tab_background #2F3549

tab_bar_background      #24283B
