[mgr]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false

ratio = [1, 3, 4]
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]


[opener]
extract = [{ run = 'ya pub extract --list "$@"', desc = "Extract here" }]
unrar = [{ run = 'unrar x "$@"', desc = "Extract here" }]

[open]
prepend_rules = [
  { url = "*.zip", use = "extract" },
  { url = "*.rar", use = "unrar" },
  { url = "*.7z", use = "extract" },
  { url = "*.tar", use = "extract" },
  { url = "*.tar.gz", use = "extract" },
]
