#!/bin/bash

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

FILE="$DIR/snip-$(date +%F-%H%M%S).png"

grimblast --freeze copysave area "$FILE"

if [ -f "$FILE" ]; then
  notify-send "Screenshot Saved" \
    "$(basename "$FILE")" \
    -i "$FILE"

  swappy -f "$FILE"
fi
