#!/bin/bash

DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"

FILE="$DIR/snip-$(date +%F-%H%M%S).png"

hyprpicker -rz &
PICKER_PID=$!
sleep 0.2

AREA=$(slurp) || { kill $PICKER_PID; exit 1; }
kill $PICKER_PID

grim -g "$AREA" "$FILE"

wl-copy < "$FILE" &
notify-send "Screenshot Saved" "$(basename "$FILE")" -i "$FILE" &
swappy -f "$FILE"
