##### GENERAL & NVIM FIX #####
set -g mouse on
set -g set-clipboard on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Better terminal support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Faster escape
set -sg escape-time 50

# Prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"


##### SESSION MANAGEMENT #####
# Session tree
bind-key s choose-tree -Zs

# Save / Restore
bind-key S run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh"
bind-key R run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh"


##### SPLIT & NAVIGATION #####
# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Window navigation
bind H previous-window
bind L next-window
bind z resize-pane -Z


##### COPY MODE (VIM STYLE) #####
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


##### TMUX POWER THEME #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


##### WINDOW STYLE #####
set -g status-justify centre

# Theme colors
set -g @tmux_power_theme '#6fa1d1'
set -g @tmux_power_g0 '#1e2530'
set -g @tmux_power_g1 '#2e3c50'
set -g @tmux_power_g2 '#2e3c50'
set -g @tmux_power_g3 '#3b4b61'
set -g @tmux_power_g4 '#6fa1d1'

# Prefix indicator
set -g @tmux_power_prefix_highlight_pos 'LR'
set -g @prefix_highlight_fg '#1e2530'
set -g @prefix_highlight_bg '#6fa1d1'
set -g @prefix_highlight_output_prefix ' ⌨ '
set -g @prefix_highlight_output_suffix ' '


##### RESURRECT / CONTINUUM #####
set -g @resurrect-dir '~/.config/tmux/resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-pane-contents-area 'full'
set -g @continuum-save-interval '15'
# set -g @continuum-restore 'on'

##### TPM #####
run '~/.config/tmux/plugins/tpm/tpm'
