##### GENERAL & NVIM FIX #####
set -g mouse on

# Jeda escape di-set aman di akhir agar tidak terganggu oleh internal plugin
set -sg escape-time 50
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Ganti prefix ke Ctrl + a (Lebih aman dibanding Ctrl + m)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

##### SPLIT & NAVIGATION (Vim Feel) #####
# Navigasi antar panel (pane)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Navigasi antar jendela (window) dengan Shift + h/l
bind H previous-window
bind L next-window

##### PANEL BORDER STYLE #####
# Gaya garis pembatas terminal agar serasi dengan Nord Blue Vibe
set -g pane-border-style fg='#2e3440'
set -g pane-active-border-style fg='#81a1c1'

##### PLUGINS (TPM & MINIMAL STATUS BAR) #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'

### Kustomisasi Plugin Minimal Tmux ###
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-bg "#81a1c1"          # Warna Nord Blue untuk window aktif
set -g @minimal-tmux-fg "#1e222a"          # Warna teks gelap di dalam komponen aktif
set -g @minimal-tmux-indicator-str " dev "  # Teks indikator di pojok kiri bawah
set -g @minimal-tmux-indicator true
# set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

# Mematikan border default bawaan plugin agar layout status bar tetap bersih
set -g @minimal-tmux-status-right "%Y-%m-%d │ %H:%M "
set -g @minimal-tmux-status-left ""

##### INITIALIZE TPM #####
# Pastikan baris ini selalu berada di paling bawah sendiri
run '~/.tmux/plugins/tpm/tpm'
