# ============================================================
# Main
# ============================================================

[main]
font=JetBrainsMono Nerd Font:size=12
pad=24x24


# ============================================================
# Cursor
# ============================================================

[cursor]
style=block
blink=yes
blink-rate=600


# ============================================================
# Scrollback
# ============================================================

[scrollback]
lines=5000


# ============================================================
# Colors
# ============================================================

[colors]
foreground=D8DEE9
background=2E3440

# Black
regular0=3B4252
bright0=4C566A

# Red
regular1=BF616A
bright1=D06F79

# Green
regular2=A3BE8C
bright2=B1D196

# Yellow
regular3=EBCB8B
bright3=F3D9A2

# Blue
regular4=81A1C1
bright4=81A1C1

# Magenta
regular5=B48EAD
bright5=C895BF

# Cyan
regular6=88C0D0
bright6=8FDFE8

# White
regular7=E5E9F0
bright7=ECEFF4

# Cursor
cursor=2E3440 81A1C1

# Selection
selection-foreground=2E3440
selection-background=81A1C1

# URL
urls=88C0D0


# ============================================================
# Keybinds
# ============================================================

[text-bindings]

\x1b[D = Alt+n
\x1b[B = Alt+u
\x1b[A = Alt+i
\x1b[C = Alt+m
